// This website is intended to build the muscle memory for starcraft 2 and other games where hotkeys
// are heavily used. On the left side of the page there is text field showing an action that the 
// user is supposed to execute. In the center there is a field showing currently prsessed keys and 
// previously pressed keys in the sequence. On the right there is a statistic showing the reaction 
// time, successful and failed operations.
// Definitions:
// - Operation - sequence of actions that lead to a particluar goal (e.g. inject first hatchery, 
//      build extractor, build lings and add to harras control group)
// - Action - single key press together with modifiers (e.g. "O", "CTRL + I", "LMB")
// - Reaction Time - time from when next operation is displayed to the user to the moment when all
//       actions are performed in proper sequence
// - Successful Operation - all actions performed from start to finish in proper order
// - Failed Operation - when at least one action is not correct in the sequence the whole sequence
//      is failed and the user needs to start from the beginning

/*
SC2Hotkeys file:

[Settings]
AllowSetConflicts=1

[Hotkeys]
FPS=Control+Shift+Alt+W
Music=Control+Shift+Alt+V
Sound=Control+Shift+Alt+SemiColon
PTT=Control+Shift+Alt+C
ChatAllies=Control+Grave
ChatDefault=Enter
ChatIndividual=Control+Shift+Enter
MenuGame=F3,Escape
AlertRecall=Control+Shift+Alt+Space
ArmySelect=Control+Shift+Alt+Y
CameraCenter=Alt
CameraFollow=Control+Shift+Alt+F8
CameraTurnLeft=Control+BackSlash
CameraTurnRight=Control+Backspace
CommanderAbility0=Shift+Alt+J,Control+Alt+J
CommanderAbility1=Shift+Alt+I,Control+Alt+I
CommanderAbility2=Shift+Alt+O,Control+Alt+O
CommanderAbility3=Shift+Alt+P,Control+Alt+P
ControlGroupAppend0=Control+Shift+Alt+Comma
ControlGroupAppend1=Control+Shift+Alt+J
ControlGroupAppend2=Control+Shift+Alt+I
ControlGroupAppend3=Control+Shift+Alt+O
ControlGroupAppend4=Control+Shift+Alt+L
ControlGroupAppend5=Control+Shift+Alt+M
ControlGroupAppend6=Control+Shift+Alt+N
ControlGroupAppend7=Control+Shift+Alt+H
ControlGroupAppend8=Control+Shift+Alt+B
ControlGroupAppend9=Control+Shift+Alt+G
ControlGroupAppendAndSteal0=Comma
ControlGroupAppendAndSteal1=Control+J
ControlGroupAppendAndSteal2=Control+I
ControlGroupAppendAndSteal3=Control+O,Alt+J
ControlGroupAppendAndSteal4=Control+L
ControlGroupAppendAndSteal5=Control+M
ControlGroupAppendAndSteal6=Control+N
ControlGroupAppendAndSteal7=Control+H
ControlGroupAppendAndSteal8=Control+B
ControlGroupAppendAndSteal9=Control+G
ControlGroupAssign0=Shift+Comma
ControlGroupAssign1=Shift+J
ControlGroupAssign2=Shift+I
ControlGroupAssign3=Shift+O
ControlGroupAssign4=Shift+L
ControlGroupAssign5=Shift+M
ControlGroupAssign6=Shift+N
ControlGroupAssign7=Shift+H
ControlGroupAssign8=Shift+B
ControlGroupAssign9=Shift+G
ControlGroupAssignAndSteal0=Control+Shift+Comma
ControlGroupAssignAndSteal1=Control+Shift+J
ControlGroupAssignAndSteal2=Control+Shift+I
ControlGroupAssignAndSteal3=Control+Shift+O
ControlGroupAssignAndSteal4=Control+Shift+L
ControlGroupAssignAndSteal5=Control+Shift+M
ControlGroupAssignAndSteal6=Control+Shift+N
ControlGroupAssignAndSteal7=Control+Shift+H
ControlGroupAssignAndSteal8=Control+Shift+B
ControlGroupAssignAndSteal9=Control+Shift+G
ControlGroupRecall0=Control+Comma
ControlGroupRecall1=J
ControlGroupRecall2=I
ControlGroupRecall3=O
ControlGroupRecall4=L
ControlGroupRecall5=M
ControlGroupRecall6=N
ControlGroupRecall7=H
ControlGroupRecall8=B
ControlGroupRecall9=G
GameTooltipsOn=Control+Shift+Alt+D
IdleWorker=6
MinimapColors=Control+Shift+Alt+3
MinimapPing=Control+Shift+Alt+X
MinimapTerrain=Control+Shift+Alt+4
QuickPing=Control+Alt+RightMouseButton
QuickSave=Control+Shift+Alt+Z
StatusAll=Control+Shift+Alt+A
StatusOwner=Control+Shift+Alt+CapsLock
StatusAlly=Control+Shift+Alt+Q
StatusEnemy=Control+Shift+Alt+Tab
SubgroupNext=ForwardMouseButton
SubgroupPrev=BackMouseButton
TargetChoose=LeftMouseButton,SemiColon,P,Slash,BracketOpen,Apostrophe,Period,Minus,BracketClose,Equals,Backspace
TownCamera=T
WarpIn=Control+Shift+Alt+F10
CameraSave0=Alt+0
CameraSave1=Alt+9
CameraSave2=Alt+8
CameraSave3=Alt+U
CameraSave4=Alt+P
CameraSave5=Alt+O
CameraSave6=Alt+I
CameraSave7=Control+0
CameraView0=0
CameraView1=9
CameraView2=8
CameraView3=U
CameraView4=Shift+9
CameraView5=Shift+8
CameraView6=Shift+U
CameraView7=Control+9

[Commands]
250mmStrikeCannons/Thor=Minus
250mmStrikeCannons/ThorWreckageSwann=Minus
ACAlarakPhasingMode/WarpPrismTaldarim=J
ACAlarakTransportMode/WarpPrismTaldarim=SemiColon
AWrp=P
AbathurDeepTunnel/SwarmHost=N
AbathurDeepTunnel/SwarmHostBurrowed=N
AbathurDeepTunnel/SwarmHostSplitB=N
AbathurDeepTunnel/SwarmHostSplitBBurrowed=N
AbathurDeepTunnel/SwarmHostSplitBRooted=N
Aberration/Larva=Apostrophe
AdeptHallucination/Sentry=BackSlash
AdeptPhaseShift/Adept=K
AdeptResearchPiercingUpgrade/TwilightCouncil=Slash
AdvancedConstructionAuto/SCV=E
Aggressive/LurkerMPBurrowed=K
AlarakDeadlyCharge/AlarakCoop=J
AlarakDeadlyCharge/AlarakReviveBeacon=J
AlarakEmpower=Minus
AlarakEmpower/AlarakCoop=Minus
AlarakEmpower/AlarakReviveBeacon=Minus
AlarakKnockback=SemiColon
AlarakKnockback/AlarakCoop=SemiColon
AlarakKnockback/AlarakReviveBeacon=SemiColon
AlarakMothershipMassTeleport/SOAMothershipv4=J
AmorphousArmorcloud/Infestor=Slash
AnionPulseCrystals/FleetBeacon=SemiColon
ApocaliskBurrowCharge/StukovApocalisk=J
Arbiter/Stargate=Y
Arbiter/StargateWarp=H
ArbiterMPRecall/ArbiterMP=J
ArbiterMPRecall/FenixArbiter=J
ArbiterMPStasisField/ArbiterMP=SemiColon
ArchonHallucination/Sentry=P
ArmorpiercingMode=K
Armory/SCV=Apostrophe
AscendantSacrifice/HighTemplarTaldarim=Minus
AssaultMode=Kjjj
Assimilator/Probe=Slash
Attack=SemiColon
AutoTurret/Raven=P
AutoTurret/Raven_BlackOps=SemiColon
AutomatedExtractor/Drone=H
AutomatedRefinery/SCV=H
Baneling/HotSRaptor=SemiColon
Baneling/HotSSwarmling=SemiColon
Baneling/Zergling=P
BanelingNest/Drone=Period
Banshee/Starport=Period
BansheeSpeed/StarportTechLab=K
Banshee_BlackOpsAirstrike/Banshee_BlackOps=J
Barracks/SCV=P
BatteryOvercharge/Nexus=
Battlecruiser/HHStarport=M
Battlecruiser/Starport=Minus
BileLauncherBombardment/BileLauncherZagara=P
BioMechanicalHeal/HealingDrone=BracketOpen
BlindingCloud/Viper=K
Blink/Stalker=K
Blink/SuperWarpGate=Y
Blink/ZeratulDarkTemplar=J
Blink/ZeratulStalker=J
BonesHeal/Stetmann=M
BrokenFenixAltarOfPsiStorms/FenixAltarOfPsiStorms=BracketOpen
BrokenSolarForge/SolarForge=P
BroodLord/Corruptor=P
BroodLord/MutaliskBroodlord=SemiColon
BroodLord/VoidRiftUnselectable=BracketClose
Brutalisk/Larva=BracketClose
BrutaliskDeepTunnel/Brutalisk=N
BuildCreepTumor/Queen=P
BuildCreepTumor/QueenCoop=Minus
BuildCreepTumorPropagate/CreepTumorBurrowed=P
BuildCyclone/Factory=Period
BuildDehakaExtractor/DehakaHatchery=H
BuildHHBomberPlatform/HHSCV=J
BuildHHMercStarport/HHSCV=J
BuildHHTechLabStarport/HHStarportFlying=Minus
BuildHercules/Starport=G
BuildKelMorianRocketTurret/SCV=M
BuildSITechLabFactory/SIFactoryFlying=Minus
BuildSITechLabStarport/SIStarportFlying=Minus
BuildScienceVessel/Starport=BracketClose
BuildTechLabFactory/FactoryFlying=BracketOpen
BuildTechLabStarport/StarportFlying=BracketOpen
BuildTychusBar/TychusSCV=BracketOpen
BuildTychusMedivacPlatform/TychusSCV=J
Bunker/SCV=BracketOpen
BunkerLoad=Minus
BunkerUnloadAll=Slash
BurrowChargeCampaign/HotSTorrasque=J
BurrowChargeCampaign/Ultralisk=J
BurrowChargeCampaignNoxious/HotSNoxious=J
BurrowDown=BracketOpen
BurrowLurkerMP=K
BurrowUp=BracketClose
CalldownMULE/OrbitalCommand=SemiColon
CampaignVehicles/Starport=Equals
Cancel=7
CancelCocoon=Slash
CancelMutateMorph=Slash
CancelUpgradeMorph=Slash
Carrier/Stargate=Period
Carrier/StargateWarp=M
Carrier/SuperWarpGate=BracketClose
CausticSpray/Corruptor=Slash
ChannelSnipe/Ghost=P
Charge/Zealot=K
Charge/ZealotAiur=Minus
Charge/ZealotPurifier=Minus
Charge/ZeratulSummonZealot=Minus
ChronoBoostEnergyCost/Nexus=Slash
CloakOff=BracketClose
CloakOnBanshee=BracketOpen
Colossus/RoboticsFacility=Apostrophe
Colossus/RoboticsFacilityWarp=BracketOpen
Colossus/SuperWarpGate=N
ColossusHallucination/Sentry=Minus
CommandCenter/HHSCV=Apostrophe
CommandCenter/SCV=Minus
CommandCenterLoad=BackSlash
CommandCenterOrbRelay/SCV=Apostrophe
CommandCenterUnloadAll=Slash
ConsumeDrone/DehakaCoopReviveCocoon=J
Contaminate/Overseer=BracketOpen
CoopMurvarSpawnCreepers/DehakaMurvar=SemiColon
CorrosiveAcidDevourer/Devourer=J
CorruptionAbility/Corruptor=J
CorruptionAbility/ZagaraCorruptor=J
Corruptor/Larva=Minus
CorsairMPDisruptionWeb/CorsairMP=J
CreepTumor/Queen=Apostrophe
CyberneticsCore/Probe=Period
CycloneResearchLockOnDamageUpgrade/FactoryTechLab=Period
DakrunCrashingCharge/DehakaDakrun=J
DarkArchon/Gateway=SemiColon
DarkArchon/WarpGate=SemiColon
DarkArchonConfusion/DarkArchon=J
DarkArchonMindControl/DarkArchon=SemiColon
DarkPylonRecall/DarkPylon=J
DarkShrine/Probe=BracketOpen
DarkTemplar=BracketOpen
DarkTemplarBlink/DarkTemplar=K
DarkTemplarShadowDash/DarkTemplarShakuras=J
DarkTemplarZeratul/ZeratulGateway=H
DeepTunnel/Queen=N
DefensiveMatrixTarget/NovaDefensiveMatrixDrone=J
DefensiveMatrixTarget/ScienceVessel=J
DehakaAirAttackUpgrade/DehakaCoop=Apostrophe
DehakaBarracks/DehakaDrone=SemiColon
DehakaBuild/DehakaDrone=J,SemiColon
DehakaConsume/DehakaCoop=BracketOpen
DehakaDakrunStructure/DehakaDrone=Minus
DehakaDeepTunnel/DehakaCoop=Minus
DehakaDrone/DehakaHatchery=Minus
DehakaGlevigRoachFireBreath/DehakaGlevigStructure=Minus
DehakaGlevigStructure/DehakaDrone=BracketOpen
DehakaGuardianMineCharge/DehakaGuardian=J
DehakaHatchery/DehakaDrone=Apostrophe
DehakaHydralisk/DehakaBarracks=H
DehakaHydraliskImpalerMerge/DehakaHydraliskLevel2=SemiColon
DehakaHydraliskToMutalisk/DehakaHydraliskLevel2=J
DehakaIntimidatingRoar/DehakaCoop=SemiColon
DehakaLeapStomp/DehakaCoop=J
DehakaLearnAbilities/DehakaCoop=Slash
DehakaLearnPrimalArmorLevel1/DehakaHatchery=J
DehakaLearnPrimalWeaponsLevel1/DehakaHatchery=P
DehakaMurvarCreeperAir/DehakaMurvarStructure=H
DehakaMurvarStructure/DehakaDrone=J
DehakaNydusDestroyer/DehakaDrone=P
DehakaNydusDestroyerTimedNoFoodBeam/DehakaNydusDestroyerTimedNoFood=J
DehakaRavasaurMerge/DehakaZerglingLevel2=SemiColon
DehakaRoach/DehakaBarracks=J
DehakaRoachGuardianMerge/DehakaRoachLevel2=J
DehakaRoachLevel2Merge/DehakaRoachLevel2=SemiColon
DehakaRoachMoveSpeed/DehakaGlevigStructure=SemiColon
DehakaSpawnLocusts/DehakaSwarmHost=SemiColon
DehakaSpawnLocusts/DehakaSwarmHostBurrowed=SemiColon
DehakaSpawnLocustsBomb/DehakaPrimalSwarmHost=SemiColon
DehakaSpawnLocustsBomb/DehakaPrimalSwarmHostBurrowed=SemiColon
DehakaSwarmHost/DehakaBarracks=Apostrophe
DehakaSwarmHostMerge/DehakaSwarmHost=J
DehakaTyrannozorFanOfKnives/DehakaUltraliskLevel3=J
DehakaUltralisk/DehakaBarracks=Equals
DehakaUltraliskCrashingCharge/DehakaUltraliskLevel2=J
DehakaUltraliskLevel2Merge/DehakaUltraliskLevel2=SemiColon
DehakaZergling/DehakaBarracks=P
DeploySpiderMines/SiegeTank_BlackOps=Minus
DetonateScourge/Scourge=J
DisableBuildingAttack/Baneling=Slash
DisableBuildingAttack/HotSSplitterlingBig=M
DisableBuildingAttackScourge/Scourge=M
DisablingCloud/Viper=J
DisruptorHallucination/Sentry=BracketOpen
DownloadBackupPart1/CybrosEscortDownloader=P
DownloadBackupPart2/CybrosEscortDownloader=J
DownloadBackupPart3/CybrosEscortDownloader=SemiColon
Drag/DehakaMirrorImage=J
Drone/Larva=P
EMP/Ghost=K
EMP/Ghost_BlackOps=J
EnableBuildingAttack/Baneling=Minus
EnableBuildingAttack/HotSHunter=Minus
EnableBuildingAttack/HotSSplitterlingBig=Minus
EnableBuildingAttackScourge/Scourge=Minus
EnableBuildingAttackVolatileInfested/SIVolatileInfested=Minus
EnergizerReclamation/SentryPurifier=BracketOpen
EngineeringBay/SCV=Apostrophe
EntropicBlast/ZeratulXelNagaConstructCyan=SemiColon
EvolutionChamber/Drone=Apostrophe
EvolveAdaptivePlating/RoachWarren=Minus
EvolveAmorphousArmorcloud/InfestationPit=K
EvolveAnabolicSynthesis2/UltraliskCavern=SemiColon
EvolveAncillaryCarapace/HydraliskDen=Minus
EvolveAncillaryCarapace/LurkerDen=Minus
EvolveBanelingCorrosiveBile/BanelingNest=J
EvolveBanelingHeal/BanelingNest=BracketOpen
EvolveBanelingRupture/BanelingNest=Minus
EvolveBileLauncherBombardmentCooldown/SpawningPool=H
EvolveBileLauncherIncreasedRange/SpawningPool=BracketOpen
EvolveBurrowCharge/UltraliskCavern=P
EvolveCentrificalHooks/BanelingNest=SemiColon
EvolveChitinousPlating/UltraliskCavern=K
EvolveCorrosiveBileDamageIncrease/RoachWarren=H
EvolveCorrosiveBileRadiusIncrease/RoachWarren=BracketOpen
EvolveDevourerAoEDamage/GreaterSpire=Apostrophe
EvolveDevourerAoEDamage/Spire=Apostrophe
EvolveDiggingClaws/LurkerDenMP=SemiColon
EvolveFrenzy/HydraliskDen=J
EvolveFrenzy/LurkerDen=J
EvolveGlialRegeneration/RoachWarren=SemiColon
EvolveGroovedSpines/HydraliskDen=K
EvolveGuardianAttackRangeIncrease/GreaterSpire=M
EvolveGuardianAttackRangeIncrease/Spire=M
EvolveHardenedCarapace/SpawningPool=SemiColon
EvolveHatcheryDoubleQueue/EvolutionChamber=BracketOpen
EvolveHydriodicBile/RoachWarren=SemiColon
EvolveInfestorEnergyUpgrade/InfestationPit=SemiColon
EvolveK5ChainLightning/EvolutionChamber=M
EvolveK5Cooldowns/EvolutionChamber=Apostrophe
EvolveKerriganHeroicFortitude/EvolutionChamber=H
EvolveKerriganViciousGlaive/GreaterSpire=BracketOpen
EvolveKerriganViciousGlaive/Spire=BracketOpen
EvolveMuscularAugments/HydraliskDen=SemiColon
EvolveMuscularAugments/LurkerDen=P
EvolveMutaliskRapidRegeneration/GreaterSpire=Minus
EvolveMutaliskRapidRegeneration/Spire=Minus
EvolvePlaguedMunitions/SIBarracksTechLab=J
EvolveSIDiamondbackImprovedEnsnare/SIFactoryTechLab=J
EvolveSIDiamondbackSnailTrail/SIFactoryTechLab=Minus
EvolveSIMarineTrooperImprovedRange/SIBarracksTechLab=P
EvolveScourgeGasCostReduction/ScourgeNest=Minus
EvolveScourgeSplashDamage/ScourgeNest=SemiColon
EvolveSeveringGlave/GreaterSpire=H
EvolveSeveringGlave/Spire=H
EvolveStukovInfestedCivilianSpawnBroodlingsOnDeath/SICivilianStructure=SemiColon
EvolveStukovInfestedInfestedCivilianLeap/SICivilianStructure=J
EvolveSunderingGlave/Spire=BracketOpen
EvolveTissueAssimilation/UltraliskCavern=SemiColon
EvolveToBrutalisk/Queen=Equals
EvolveToBrutalisk/QueenBurrowed=Equals
EvolveToBrutalisk/RavagerAbathur=Equals
EvolveToBrutalisk/Roach=Equals
EvolveToBrutalisk/RoachBurrowed=Equals
EvolveToBrutalisk/RoachVile=Equals
EvolveToBrutalisk/RoachVileBurrowed=Equals
EvolveToBrutalisk/SwarmHost=Equals
EvolveToBrutalisk/SwarmHostBurrowed=Equals
EvolveToLeviathan/Devourer=Equals
EvolveToLeviathan/GuardianMP=Equals
EvolveToLeviathan/Mutalisk=Equals
EvolveToLeviathan/Viper=Equals
EvolveTunnelingClaws/RoachWarren=P
EvolveVentralSacks=G
EvolveViperImprovedCastRange/InfestationPit=SemiColon
EvolveZerglingArmorShred/SpawningPool=Minus
Explode/Baneling=K
Explode/BanelingBurrowed=J
Explode/HotSHunter=J
Explode/HotSHunterBurrowed=J
Explode/HotSSplitterlingBig=J
Explode/HotSSplitterlingBigBurrowed=J
ExplodeVolatileInfested/SIVolatileInfested=J
ExplosiveMode=P
Extractor/Drone=Slash
FaceEmbrace/Viper=P
Factory/SCV=K
Feedback/Archon=M
Feedback/HighTemplar=Slash
Feedback/ZeratulSummonKarass=M
FenixArbiterCloakField/FenixArbiter=Minus
FenixArbiterStasisField/FenixArbiter=SemiColon
FenixClolarionBomberDummy/FenixClolarionCarrier=BracketOpen
FenixClolarionCarrierDownloadUpgrade=M
FenixClolarionInterceptor/FenixClolarionCarrier=Minus
FenixDragoonAirBomb/FenixDragoon=SemiColon
FenixDragoonArsenalOvercharge/FenixDragoon=Minus
FenixDragoonChargedBuster/FenixDragoon=J
FenixImmortalResearchDetonationShot/RoboticsBay=BracketOpen
FenixKaldalisZealotCharge/FenixKaldalisZealot=J
FenixKaldalisZealotDownloadUpgrade=P
FenixMojoMissiles/FenixMojoScout=J
FenixMojoScoutDownloadUpgrade=Minus
FenixPurificationNova/Disruptor=J
FenixSentryGuardianZone/SentryFenix=Minus
FenixTaldarinImmortalDownloadUpgrade=SemiColon
FenixTalisAdeptBounceShot/FenixTalisAdept=J
FenixTalisAdeptDownloadUpgrade=J
FenixThunderousChargeCoop/FenixCoop=J
FenixWarbringerColossusDownloadUpgrade=BracketOpen
FenixWarbringerColossusPowerShot/FenixWarbringerColossus=J
FenixWhirlwind/FenixCoop=SemiColon
FighterMode=P
Firebat/Barracks=Apostrophe
FleetBeacon/Probe=Period
FleetwideJump/HHRaven=N
FleetwideJump/HHVikingAssault=N
FleetwideJump/HHVikingFighter=N
FleetwideJump/HHWraith=N
ForceField/Sentry=K
Forge/Probe=Apostrophe
FungalGrowth/Infestor=K
FungalGrowth/InfestorBurrowed=J,N
FusionCore/HHSCV=M
FusionCore/SCV=Period
Gateway/Probe=P
GatherProt=Equals
GenerateCreep/Overlord=BracketOpen
GenerateCreep/OverlordTransport=BracketOpen
Ghost/Barracks=Apostrophe
GhostAcademy/SCV=P
GhostHoldFire/Ghost=Slash
GhostHoldFire/Ghost_BlackOps=H
GhostHoldFire/NovaCoop=H
GlevigFirebreath/DehakaGlevig=J
GlevigTunnel/DehakaGlevig=Minus
Goliath/Factory=Y
GravitonBeam/Phoenix=P,K
GravitonBeam/PhoenixPurifier=J,SemiColon
GreaterNydusDestroyerDeepTunnel/DehakaNydusDestroyerTimedNoFood=N
GreaterSpire/Spire=P
GreaterSpireBroodlord/Spire=SemiColon
GuardianShield/Sentry=BracketOpen
GuardianShield/SentryAiur=Minus
HHArmory/HHSCV=Minus
HHBattlecruiserShots/HHBattlecruiser=SemiColon
HHBomberAreaBomb/HHBomberPlatform=P
HHHellion/HHMercStarportUpgraded=Minus
HHHellionBomb/HHHellion=Minus
HHHellionTank/HHMercStarportUpgraded=BracketOpen
HHKD8Charge/HHReaper=J
HHMercCompound/HHSCV=Minus
HHNomadTargetLock/HHRaven=Minus
HHRaven/HHStarport=H
HHReaper/HHMercStarportUpgraded=SemiColon
HHReaperFly/HHReaper=SemiColon
HHTechLabStarport/HHStarport=Minus
HHVikingRockets/HHVikingFighter=SemiColon
HHWidowMine/HHMercStarportUpgraded=J
HHYamatoShots/HHBattlecruiser=J
Hallucination/Sentry=P,Slash
Halt=BracketClose
Hatchery/Drone=Minus
Heal/Medivac=BracketOpen
HellbatJumpJetAssault/HellionBlackOps=Minus
HellfireThrusters/StarportTechLab=J
Hellion/Factory=SemiColon
HellionTank/Factory=Minus
HerculesLoad/Hercules=M
HerculesUnloadAll/Hercules=BracketOpen
HeroNukeCalldown/Nova=Apostrophe
HeroNukeCalldown/Tosh=Apostrophe
HighTemplar=Apostrophe
HighTemplarHallucination/Sentry=Apostrophe
HireDevilDogs/Barracks=D
HireHammerSecurities/Barracks=H
HireHelsAngels/Starport=J
HireKelmorianMiners/Barracks=W
HireSiegeBreakers/Factory=W
HireSpartanCompany/Factory=E
Hive/Lair=Backspace
HiveMindEmulator/SCV=N
HotSBioPlasmidDischarge/HotSLeviathan=J
HotSBioStasis/HotSLeviathan=M
HotSPressurizedGlands/InfestationPit=J
Hydralisk/Larva=BracketOpen
HydraliskDen/Drone=K
HydraliskFrenzy/Hydralisk=J
HydraliskFrenzy/HydraliskImpaler=J
HydraliskFrenzy/HydraliskLurker=J
HyperionAdvancedPDD/HyperionVoidCoop=Minus
HyperionKorhalRegen/HyperionKorhal=M
HyperionKorhalRegenOff/HyperionKorhal=Minus
HyperionKorhalYamato/HyperionKorhal=SemiColon
HyperionVoidCoopHyperjump/HyperionVoidCoop=N
HyperionVoidCoopYamatoCannon/HyperionVoidCoop=SemiColon
Hyperjump/Battlecruiser=BracketOpen
Hyperjump/HHBattlecruiser=N
HyperjumpHercules/Hercules=N
IgniteAfterburner/Medivac=K
IgniteAfterburners/Banshee=N
IgniteAfterburners/Battlecruiser=N
IgniteAfterburners/SiegeTank=N
IgniteAfterburners/VikingAssault=N
IgniteAfterburners/Vulture=N
Immortal/RoboticsFacility=SemiColon
Immortal/RoboticsFacilityWarp=J
Immortal/SuperWarpGate=J
ImmortalHallucination/Sentry=Period
ImmortalOverload/FenixTaldarinImmortal=J
ImmortalOverload/Immortal=J
ImmortalOverload/ZeratulImmortal=J
ImmortalShakurasShadowCannon/Immortal=SemiColon
ImmortalShakurasShadowCannon/ImmortalShakuras=SemiColon
ImmortalZeratul/ZeratulRoboticsFacility=J
Impaler/HydraliskImpaler=SemiColon
ImpalerBurrowDown=J
ImpalerBurrowUp=SemiColon
InfestationPit/Drone=P
InfestedTerrans/Infestor=SemiColon
InfestedTerrans/InfestorBurrowed=SemiColon
Infestor/Larva=Apostrophe
InfestorConsumption/Infestor=Minus
InstantHunterSeekerMissile/Raven=J,BracketOpen
InstantHunterSeekerMissile/Raven_BlackOps=J,H
Interceptor/Carrier=K
Irradiate/ScienceVessel=SemiColon
KD8Charge/Reaper=P
KerriganVoidCoopCrushingGripWave/K5Kerrigan=M
KerriganVoidCoopCrushingGripWave/K5KerriganBurrowed=M
KerriganVoidCoopEconDrop/K5Kerrigan=Minus
KerriganVoidCoopEconDrop/K5KerriganBurrowed=Minus
KhaydarinMonolith/Probe=N
Lair/Hatchery=Backspace
Land=Backspace
Larva=K,SemiColon,P,Slash,BracketOpen,Period,Minus,BracketClose
LearnDehakaArmorUpgrade/DehakaCoop=M
LearnDehakaConsume/DehakaCoop=BracketOpen
LearnDehakaDetector/DehakaCoop=Minus
LearnDehakaIntimidatingRoar/DehakaCoop=SemiColon
LearnDehakaLeapStomp/DehakaCoop=J
LearnDehakaMammothBreath/DehakaCoop=H
LearnDehakaMendingAura/DehakaCoop=P
Liberator/Starport=P
LiberatorAAMode/Liberator=P
LiberatorAGMode/Liberator=BracketOpen,K
Liberator_BlackOpsMorphtoAA/Liberator_BlackOps=SemiColon
Liberator_BlackOpsMorphtoAG/Liberator_BlackOps=J
Lift=Backspace
LightningBomb/Tempest=J
LightningBomb/TempestPurifier=J
LockOn/Cyclone=K
LocustFlyingLaunch/SwarmHostSplitABurrowed=SemiColon
LocustFlyingLaunch/SwarmHostSplitARooted=SemiColon
LocustLaunch/SwarmHost=SemiColon
LocustLaunch/SwarmHostBurrowed=SemiColon
LocustLaunch/SwarmHostRooted=SemiColon
LocustLaunchCreeper/SwarmHostSplitBBurrowed=SemiColon
LocustLaunchCreeper/SwarmHostSplitBRooted=SemiColon
LocustMPFlyingSwoop/LocustMPFlying=K
Lower/SupplyDepot=P
Lurker/HydraliskLurker=SemiColon
LurkerBurrowUp=P
LurkerCancelHoldFire/LurkerBurrowed=BracketOpen
LurkerCancelHoldFire/LurkerMP=BracketOpen
LurkerCancelHoldFire/LurkerMPBurrowed=Minus
LurkerDen/HydraliskDen=SemiColon
LurkerHoldFire/LurkerBurrowed=H
LurkerHoldFire/LurkerMP=Slash
LurkerHoldFire/LurkerMPBurrowed=BracketOpen
LurkerMP/Hydralisk=P
MagrailMunitions/Marauder_BlackOps=J
MammothBreath/DehakaCoop=H
Marauder/Barracks=P
Marine/Barracks=SemiColon
MarineSuperStimpack/Marine_BlackOps=J
MassRecall/Mothership=P
MassRoachDrop/ZagaraVoidCoop=Minus
MassRoachDrop/ZagaraVoidCoopBurrowed=Minus
Medic/Barracks=M
MedicHeal/Medic=M
MedicHeal/Medivac_BlackOps=Minus
Medivac/Starport=Slash
MedivacSpeedBoost/Medivac=K
MedivacSpeedBoost/Medivac_BlackOps=J
MercCompound/SCV=SemiColon
MercHellion/Factory=X
MercMedic/Barracks=N
MercMedicHeal/MercMedic=M
MercReaper/Barracks=G
MicroBot/Factory=C
MindBlast/Spectre=J
MindBolt/K5Kerrigan=J
MindBolt/K5KerriganBurrowed=J
MissileTurret/HHSCV=P
MissileTurret/SCV=SemiColon
MorphBackToGateway/WarpGate=C
MorphBackToRoboticsFacility/RoboticsFacilityWarp=C
MorphBackToStargate/StargateWarp=C
MorphMorphalisk/Queen=Slash
MorphMorphalisk/QueenCoop=J,SemiColon
MorphToGuardian/Mutalisk=SemiColon
MorphToHHHellion/HHHellionTank=SemiColon
MorphToHellbatBlackOps/HellionBlackOps=J
MorphToHellion/Hellion=P
MorphToHellion/HellionBlackOps=SemiColon
MorphToHellionTank/HHHellion=J
MorphToHellionTank/Hellion=K
MorphToMothership/MothershipCore=BracketOpen
MorphToOverseer/Overlord=P
MorphToOverseer/OverlordTransport=P
MorphToOverseer/SIOverlord=SemiColon
MorphtoDevourer/Mutalisk=J
MorphtoHHRaven/HHRaven=SemiColon
MorphtoHHRavenSiege/HHRaven=J
MorphtoObserver/Observer=P
MorphtoObserver/ZeratulObserver=SemiColon
MorphtoObserverSiege/Observer=K
MorphtoObserverSiege/ZeratulObserver=J
MorphtoOverlordTransport/Overlord=K
MorphtoOverseerNormal/Overseer=P
MorphtoOverseerSiege/Overseer=K
MorphtoRoach/Larva=SemiColon
Mothership/Nexus=Apostrophe
MothershipCoreMassRecall/MothershipCore=J
MothershipCoreWeapon/MothershipCore=Minus
MothershipMassRecall/Mothership=SemiColon
Move=A
MoveHoldPosition=Apostrophe
MovePatrol=Y
MurvarPukeCoop/DehakaMurvar=J
MuscularAugments/HydraliskDen=J
Mutalisk/Larva=Period
MutateintoLurkerDen/Drone=BracketOpen
NanoRepair/ScienceVessel=M
NeuralParasite/Infestor=P
NeuralParasite/InfestorBurrowed=Minus
Nexus/Probe=Minus
NexusMassRecall/Nexus=K
NovaBoombotBurrow/NovaBoombot=J
NovaGadgetBoombots=J
NovaGadgetBoombots/NovaCoop=J
NovaGadgetBoombots/NovaReviveBeacon=J
NovaSwitchAssaultMode=Minus
NovaSwitchAssaultMode/NovaCoop=Minus
NovaSwitchAssaultMode/NovaReviveBeacon=Minus
NovaUnitNuke=Apostrophe
NovaUnitNuke/NovaCoop=Apostrophe
NovaUnitNuke/NovaReviveBeacon=Apostrophe
NovaWeaponImprovedCanisterRifleSnipe=SemiColon
NovaWeaponImprovedCanisterRifleSnipe/NovaCoop=SemiColon
NovaWeaponImprovedCanisterRifleSnipe/NovaReviveBeacon=SemiColon
NukeArm/GhostAcademy=SemiColon
NukeCalldown/Ghost=Equals
NukeCalldown/Spectre=Apostrophe
NydusDestroyerBeam/DehakaNydusDestroyer=J
NydusDestroyerDeepTunnel/DehakaNydusDestroyer=N
NydusNetwork/Drone=Apostrophe
Observer/RoboticsFacility=P
Observer/RoboticsFacilityWarp=P
OdinNukeCalldown/Odin=Apostrophe
Oracle/Stargate=P
Oracle/StargateWarp=J
OracleAttack=SemiColon
OracleBuildStasisTrap/Oracle=BracketOpen
OracleHallucination/Sentry=K
OracleRevelation/Oracle=Slash
OracleWeaponOff/Oracle=P
OracleWeaponOn/Oracle=K
OrbitalCommand/CommandCenter=SemiColon
OrbitalCommandCalldownSupplyDepot/OrbitalCommand=SemiColon
Overlord/Larva=Slash
ParasiticBomb/Viper=Slash
PhasingMode/WarpPrism=K
PhasingMode/ZeratulWarpPrism=J
Phoenix/Stargate=SemiColon
Phoenix/StargateWarp=P
Phoenix/SuperWarpGate=Apostrophe
PhoenixHallucination/Sentry=SemiColon
PhotonCannon/Probe=SemiColon
PlanetCracker/MothershipAiur06=J
PlanetCrackerOff/MothershipAiur06=SemiColon
PointDefenseDrone/Raven=Minus
PointDefenseDrone/Raven_BlackOps=Minus
PoisonNova/HotSNoxious=SemiColon
Predator/Factory=A
PrimalBuildingRoot/DehakaBarracksUprooted=N
PrimalBuildingRoot/DehakaHatcheryUprooted=N
PrimalBuildingUproot/DehakaBarracks=N
PrimalBuildingUproot/DehakaHatchery=N
PrimalHydralisk/PrimalTownHall=H
PrimalMutalisk/PrimalTownHall=M
PrimalRoach/PrimalTownHall=J
PrimalUltralisk/PrimalTownHall=Equals
PrimalZergling/PrimalTownHall=SemiColon
PrimalZergling/YagdraEggSmall=SemiColon
Probe/Nexus=P
ProbeHallucination/Sentry=Backspace
ProphecyVision/ZeratulCoop=Minus
ProtossAirArmorLevel1/CyberneticsCore=K
ProtossAirWeaponsLevel1/CyberneticsCore=SemiColon
ProtossBuild/Probe=K,P
ProtossBuildAdvanced/Harvester=Slash
ProtossBuildAdvanced/Probe=Slash
ProtossGroundArmorLevel1/Forge=K
ProtossGroundWeaponsLevel1/Forge=SemiColon
ProtossShieldsLevel1/Forge=P
PsiStorm/Archon=J
PsiStorm/HighTemplar=K
PsiStormTelbrus/ZeratulSummonKarass=J
PsionicLift/K5Kerrigan=SemiColon
PsionicLift/K5KerriganBurrowed=SemiColon
PsionicLift/KerriganGhostLab=J
PurificationNovaTargeted/Disruptor=K
Pylon/Probe=K
Queen=Apostrophe
QueenBurstHeal/Queen=M
QueenClassicParasite/SIQueen=Minus
QueenMPSpawnBroodlings/SIQueen=SemiColon
Raise/SupplyDepotLowered=K
Rally=Z
RallyEgg=D
RallySCV=F
Ravager/Roach=P
Ravager/RoachCorpser=SemiColon
Ravager/RoachVile=SemiColon
RavagerAbathurCorrosiveBile/RavagerAbathur=SemiColon
RavagerCorrosiveBile/Ravager=P
Raven/Starport=Apostrophe
RavenRepairDrone/Raven=SemiColon
RavenRepairDroneHeal/RavenRepairDrone=J
RavenResearchEnhancedMunitions/StarportTechLab=BracketOpen
RavenScramblerMissile/Raven=K
RavenShredderMissile/Raven=BracketOpen
Reactor/Barracks=K
Reactor/BarracksFlying=K
Reactor/Factory=K
Reactor/FactoryFlying=K
Reactor/Starport=K
Reactor/StarportFlying=K
Reaper/Barracks=Slash
ReaverScarabs/Reaver=Minus
Refinery/HHSCV=H
Refinery/SCV=Slash
Repair=BracketOpen
RepairDrones/Carrier=J
Research330mmBarrageCannon/FactoryTechLab=M
Research330mmBarrageCannon/FactoryTechReactor=M
ResearchAlarakTargetLockBuff/CyberneticsCore=Minus
ResearchAutoCreateInfestedCivilianAmmo/SIFactoryTechLab=SemiColon
ResearchBallisticRange/FusionCore=K
ResearchBansheeCloak/StarportTechLab=BracketOpen
ResearchBansheeCloak/StarportTechReactor=Minus
ResearchBarrelStabilizers/BarracksTechLab=J
ResearchBattlecruiserSpecializations/FusionCore=P
ResearchBurrow=BackSlash
ResearchCharge/TwilightCouncil=SemiColon
ResearchCycloneLockOnDamageUpgrade/FactoryTechLab=H
ResearchCycloneLockOnDamageUpgrade/FactoryTechReactor=H
ResearchCycloneRapidFireLaunchers/FactoryTechLab=BracketOpen
ResearchDarkArchonFullStartingEnergy/DarkShrine=BracketOpen
ResearchDarkArchonMindControl/DarkShrine=H
ResearchDarkTemplarBlink/DarkShrine=K
ResearchDehakaGuardianExplosiveBomb/DehakaMurvarStructure=Minus
ResearchDehakaGuardianFury/DehakaMurvarStructure=BracketOpen
ResearchDehakaHydraliskSpeed/DehakaGlevigStructure=BracketOpen
ResearchDehakaImpalerTenderize/DehakaGlevigStructure=H
ResearchDehakaMutaliskDamageReduction/DehakaMurvarStructure=J
ResearchDehakaMutaliskRespawnOnDeath/DehakaMurvarStructure=SemiColon
ResearchDehakaRavasaurRange/DehakaGlevigStructure=J
ResearchDehakaRavasaurVSArmor/DehakaGlevigStructure=P
ResearchDehakaTyrannozorArmorAura/DehakaDakrunStructure=BracketOpen
ResearchDehakaTyrannozorFanOfKnives/DehakaDakrunStructure=Minus
ResearchDehakaUltraliskBash/DehakaDakrunStructure=SemiColon
ResearchDehakaUltraliskCrashingCharge/DehakaDakrunStructure=P
ResearchDehakaUltraliskRegen/DehakaDakrunStructure=J
ResearchDoubleGravitonBeam/FleetBeacon=J
ResearchDragoonChassis/TwilightCouncil=BracketOpen
ResearchDragoonRange/TwilightCouncil=Minus
ResearchDrakkenLaserDrillBFG/DrakkenLaserDrillCoop=J
ResearchDrillClaws/FactoryTechLab=P
ResearchEnhancedShockwaves/GhostAcademy=K
ResearchExtendedThermalLance/RoboticsBay=K
ResearchFenixWarbringerColossusPowerShot/RoboticsBay=H
ResearchFireSuppressionSystems/EngineeringBay=BracketOpen
ResearchGhostEnergyUpgrade/GhostAcademy=P
ResearchGraviticBooster/RoboticsBay=SemiColon
ResearchGraviticDrive/RoboticsBay=Slash
ResearchHHBomberNapalm/FusionCore=P
ResearchHHHellionAttackDoT/HHMercCompound=N
ResearchHHHellionDeathFear/HHMercCompound=Apostrophe
ResearchHHHellionDeathStim/HHMercCompound=H
ResearchHHHellionRocket/HHMercCompound=M
ResearchHHMercStarportHangarBay/HHMercStarportUpgraded=H
ResearchHHReaperClusterBombs/HHMercCompound=Minus
ResearchHHReaperFlight/HHMercCompound=SemiColon
ResearchHHTacticalJumpCharges/StarportTechLab=Equals
ResearchHHWidowMineDeathBlossom/HHMercCompound=J
ResearchHHWidowMineRangeAttack/HHMercCompound=BracketOpen
ResearchHealingPsionicStorm/TemplarArchive=SemiColon
ResearchHeavyInfestation/SICommandCenter=P
ResearchHellbatHellArmor/FactoryTechLab=Apostrophe
ResearchHellbatHellArmor/FactoryTechReactor=Apostrophe
ResearchHiSecAutoTracking/EngineeringBay=P
ResearchHighCapacityBarrels/FactoryTechLab=SemiColon
ResearchHighCapacityBarrels/FactoryTechReactor=P
ResearchHighCapacityFuelTanks/StarportTechLab=SemiColon
ResearchHighTemplarEnergyUpgrade/TemplarArchive=P
ResearchImprovedSiegeMode/FactoryTechLab=SemiColon
ResearchImprovedSiegeMode/FactoryTechReactor=SemiColon
ResearchImprovedTurretAttackSpeed/EngineeringBay=H
ResearchIncineratorGauntlets/BarracksTechLab=Apostrophe
ResearchIncineratorGauntlets/BarracksTechReactor=Apostrophe
ResearchInfestedBunkerArmor/SIEngineeringBay=Minus
ResearchInfestedBunkerLifeRegen/SIEngineeringBay=SemiColon
ResearchInfestedSiegeTankArmoredDamage/SIFactoryTechLab=BracketOpen
ResearchInterceptorLaunchSpeedUpgrade/FleetBeacon=J
ResearchJuggernautPlating/BarracksTechLab=BracketOpen
ResearchJuggernautPlating/BarracksTechReactor=BracketOpen
ResearchKaraxTurretAttackSpeed/Forge=BracketOpen
ResearchKaraxTurretRange/Forge=Minus
ResearchLockOnRangeUpgrade/FactoryTechLab=BracketOpen
ResearchLockOnRangeUpgrade/FactoryTechReactor=BracketOpen
ResearchLurkerRange/HydraliskDen=BracketOpen
ResearchLurkerRange/LurkerDen=BracketOpen
ResearchLurkerRange/LurkerDenMP=K
ResearchMaelstromRounds/FactoryTechLab=Minus
ResearchMaelstromRounds/FactoryTechReactor=Minus
ResearchMarauderMagrailMunitions/BarracksTechLab=Minus
ResearchMarauderMagrailMunitions/BarracksTechReactor=Minus
ResearchMedivacCloakedHealBeam/StarportTechLab=Apostrophe
ResearchMedivacCloakedHealBeam/StarportTechReactor=M
ResearchMultiLockWeaponsSystem/FactoryTechLab=J
ResearchMultiLockWeaponsSystem/FactoryTechReactor=J
ResearchNeosteelFrame/EngineeringBay=M
ResearchNeuralParasite/InfestationPit=P
ResearchNovaDetector/GhostAcademyNova=P
ResearchNovaLifeRegen/GhostAcademyNova=J
ResearchNovaShotgunBlastRange/GhostAcademyNova=Minus
ResearchNovaSnipeRefund/GhostAcademyNova=SemiColon
ResearchOracleStasisWardUpgrade/FleetBeacon=Minus
ResearchPersonalCloaking/GhostAcademy=BracketOpen
ResearchPhobosClassWeaponsSystem/StarportTechLab=P
ResearchPhobosClassWeaponsSystem/StarportTechReactor=P
ResearchPiercingRockets/StarportTechLab=K
ResearchPsiStorm/TemplarArchive=K
ResearchPunisherGrenades/BarracksTechLab=P
ResearchPunisherGrenades/BarracksTechReactor=J
ResearchRapidReignitionSystem/FusionCore=Slash
ResearchRavenEnergyUpgrade/StarportTechLab=SemiColon
ResearchRavenInterferenceMatrix/StarportTechLab=
ResearchReaverIncreasedScarabCount/RoboticsBay=J
ResearchReaverIncreasedScarabSplashRadius/RoboticsBay=SemiColon
ResearchRegenerativeBioSteel/Armory=Minus
ResearchRipwaveMissiles/StarportTechLab=BracketClose
ResearchRipwaveMissiles/StarportTechReactor=J
ResearchSIBarracksTrainInfestedCivilianLevel2/SICivilianStructure=P
ResearchSILiberatorBecometheSwarm/SIStarportTechLab=J
ResearchSILiberatorImprovedAoeAttack/SIStarportTechLab=SemiColon
ResearchSIQueenEnergy/SIStarportTechLab=M
ResearchSIQueenFungalGrowth/SIStarportTechLab=H
ResearchSOAOrbitalStrikeUpgrade/SolarForge=SemiColon
ResearchSOARepairBeamExtraTarget/SolarForge=J
ResearchSOASolarLanceUpgrade/SolarForge=Minus
ResearchShadowDash/DarkShrine=J
ResearchShadowFury/DarkShrine=P
ResearchShieldWall/BarracksTechLab=SemiColon
ResearchShieldWall/BarracksTechReactor=SemiColon
ResearchShockwaveMissileBattery/StarportTechLab=BracketOpen
ResearchShockwaveMissileBattery/StarportTechReactor=BracketOpen
ResearchSlicingGlave/DehakaMurvarStructure=P
ResearchSmartServos/FactoryTechLab=Apostrophe
ResearchSolarEfficiencyLevel1/SolarForge=P
ResearchStabilizerMedpacks/BarracksTechLab=Minus
ResearchStabilizerMedpacks/BarracksTechReactor=Minus
ResearchStalkerTeleport/TwilightCouncil=P
ResearchStructureBarrier/Forge=H
ResearchStukovInfestedBansheeBurrowRegeneration/SIStarportTechLab=BracketOpen
ResearchStukovInfestedBansheeInfestedLife/SIStarportTechLab=Minus
ResearchSuperScience/StarportTechReactor=SemiColon
ResearchTempestDisintegration/FleetBeacon=SemiColon
ResearchTransformationServos/FactoryTechLab=SemiColon
ResearchVehicleWeaponRange/Armory=SemiColon
ResearchVoidRaySpeedUpgrade/FleetBeacon=K
ResearchVoidStasis/DarkShrine=Minus
ResearchWarpGate/CyberneticsCore=P
ResearchWhirlwind/TwilightCouncil=SemiColon
RespawnZergling/Hatchery=W
RespawnZergling/Hive=W
RespawnZergling/Lair=W
ReturnCargo=Minus
Roach/Larva=K
RoachWarren/Drone=P
RoboticsBay/Probe=Minus
RoboticsFacility/Probe=K
RogueGhostCloak/Spectre=Minus
SCV=P
SIArmory/SISCV=Minus
SIBanshee/SIStarport=BracketOpen
SIBarracks/SISCV=BracketOpen
SICivilianStructure/SISCV=M
SIClusterRockets/StukovApocalisk=SemiColon
SICommandCenter/SISCV=Apostrophe
SIDiamondBack/SIFactory=G
SIEngineeringBay/SISCV=Minus
SIFactory/SISCV=P
SIInfestedBunker/SISCV=J
SIInfestedBunkerRoot/SIInfestedBunkerUprooted=N
SIInfestedBunkerSpawnInfestedMarine/SIInfestedBunker=SemiColon
SIInfestedBunkerUproot/SIInfestedBunker=N
SIInfestedCivilian/SICivilianStructure=Minus
SIInfestedCivilian/SICivilianStructureFlying=Minus
SIInfestedMarine/SIBarracks=SemiColon
SILiberator/SIStarport=SemiColon
SIMissileTurret/SISCV=P
SIOverlord/SICommandCenter=SemiColon
SIQueen=H
SIQueenFungalGrowth/SIQueen=J
SIRefinery/SISCV=H
SIRoot/SIBarracksFlying=N
SIRoot/SICivilianStructureFlying=N
SIRoot/SICommandCenterFlying=N
SIRoot/SIFactoryFlying=N
SIRoot/SIMissileTurretFlying=N
SIRoot/SIStarportFlying=N
SISCV=Minus
SISiegeTank/SIFactory=SemiColon
SIStarport/SISCV=J
SIStukovPlaceHordeRally/SIBarracks=D
SIStukovPlaceHordeRally/SIInfestedBunker=D
SITechLabBarracks/SIBarracks=Minus
SITechLabBarracks/SIBarracksFlying=Minus
SITechLabFactory/SIFactory=Minus
SITechLabStarport/SIStarport=Minus
SIUproot/SIBarracks=N
SIUproot/SICivilianStructure=N
SIUproot/SICommandCenter=N
SIUproot/SIFactory=N
SIUproot/SIMissileTurret=N
SIUproot/SIStarport=N
SJHyperionBlink/SJHyperion=J
SJHyperionFighters/SJHyperion=Minus
SJHyperionFightersRecall/SJHyperion=M
SJHyperionYamato/SJHyperion=SemiColon
SOAMothershipLineAttack/SOAMothershipv4=SemiColon
Salvage/Bunker=P
Salvage/KelMorianGrenadeTurret=SemiColon
Salvage/KelMorianMissileTurret=SemiColon
Salvage/MissileTurret=M
Salvage/NovaACLaserTurret=SemiColon
Salvage/PerditionTurret=SemiColon
Salvage/PerditionTurretUnderground=SemiColon
Salvage/SIMissileTurret=M
Salvage/SIMissileTurretFlying=M
Salvage/TychusSCVAutoTurret=M
Scan/OrbitalCommand=K
Scourge/Larva=N
ScourgeNest/Drone=M
SelectBuilder=C
SelfRepair/Thor=BracketOpen
SelfRepair/ThorWreckageSwann=BracketOpen
SensorTower/SCV=Period
Sentry=Period
SentryTaldarimForceField/Monitor=J
SentryZeratul/ZeratulGateway=J
SetBunkerRallyPoint/Bunker=X
ShadowGuardBlink/VorazunShadowGuard=J
ShieldBattery/Probe=BracketOpen
ShieldBatteryRecharge/ShieldBattery=K
ShieldBatteryStructureBarrier/ShieldBattery=J
SiegeMode=K
SiegeTank/Factory=Slash
SiegeTank_BlackOpsSiege=J
SiegeTank_BlackOpsUnsiege=SemiColon
Snipe/Ghost=SemiColon
Snipe_BlackOps/Ghost_BlackOps=SemiColon
SpawnChangeling/Overseer=Slash
SpawningPool/Drone=K
Spectre/Barracks=G
SpectreDomination/Spectre=Minus
SpectreHoldFire/Spectre=H
SpectreNukeArm/GhostAcademy=Apostrophe
SpectreNukeCalldown/Spectre=Apostrophe
SpectreWeaponsFree/Spectre=BracketOpen
SpiderMine/Reaper=J
SpiderMine/Vulture=J
SpiderMineReplenish/Vulture=SemiColon
SpineCrawler/Drone=BracketOpen
SpineCrawlerRoot/SpineCrawlerUprooted=K
SpineCrawlerUproot/SpineCrawler=SemiColon
SpineCrawlerUproot/SpineCrawlerUprooted=P
Spire/Drone=SemiColon
SporeCrawler/Drone=SemiColon
SporeCrawlerRoot/SporeCrawlerUprooted=K
SporeCrawlerUproot/SporeCrawler=SemiColon
SporeCrawlerUproot/SporeCrawlerUprooted=P
Spray=BackSlash
Stalker=P
StalkerBlinkShieldRestoreBase/StalkerShakuras=J
StalkerHallucination/Sentry=Space
StalkerZeratul/ZeratulGateway=Minus
Stargate/Probe=SemiColon
Starport/SCV=SemiColon
Stim=K
StimFirebat/DevilDog=J
StimFirebat/Firebat=J
Stimpack/BarracksTechLab=K
Stimpack/BarracksTechReactor=P
Stop=Period
StopGenerateCreep=Minus
StopGenerateCreep/Overlord=M
StopPlanetaryFortress/PlanetaryFortress=Equals
StukovInfestedDiamondbackSnare/StukovInfestedDiamondBack=J
StukovInfestedSiegeTankDeepTunnel/StukovInfestedSiegeTank=Minus
StukovInfestedSiegeTankRoot/StukovInfestedSiegeTank=J
StukovInfestedSiegeTankUproot/StukovInfestedSiegeTank=SemiColon
Summon2ScoutHallucinations/Sentry=J
SummonNydusWorm/NydusNetwork=P
SupplyDepot/HHSCV=SemiColon
SupplyDepot/SCV=K
SupplyDepotDrop/SCV=SemiColon
SupplyDrop/OrbitalCommand=Slash
SwannCommanderRebuild=BracketOpen
SwarmHostBurrowDown=BracketOpen
SwarmHostBurrowUp=H
SwarmHostMP/Larva=BracketClose
SwarmHostRoot=BracketOpen
SwarmHostRootBurrow=BracketOpen
SwarmHostUproot=H
SwarmHostUprootUnburrow=H
SwarmQueenParasiticInvasion/HugeSwarmQueen=Minus
SwarmQueenParasiticInvasion/LargeSwarmQueen=Minus
SwarmQueenParasiticInvasion/SwarmQueen=Minus
SwarmQueenRaptor/HugeSwarmQueen=SemiColon
SwarmQueenRaptor/LargeSwarmQueen=SemiColon
SwarmQueenRoach/HugeSwarmQueen=J
SwarmQueenSwarmling/HugeSwarmQueen=SemiColon
SwarmQueenSwarmling/LargeSwarmQueen=SemiColon
SwarmQueenZergling/HugeSwarmQueen=SemiColon
SwarmQueenZergling/SwarmQueen=SemiColon
SymbioteCarapace/Brutalisk=J
TargetLock/Monitor=SemiColon
TechLabBarracks/Barracks=BracketOpen
TechLabBarracks/BarracksFlying=BracketOpen
TechLabFactory/Factory=BracketOpen
TechLabStarport/Starport=BracketOpen
TechReactorAI/Barracks=Y
TechReactorAI/Factory=Q
TechReactorAI/Starport=Q
Tempest/Stargate=BracketOpen
TempestResearchGroundAttackUpgrade/FleetBeacon=
TemplarArchive/Probe=P
TemporalField/Mothership=K
TemporalField/MothershipCore=SemiColon
TerranBuild=K,P
TerranBuild/HHSCV=J,SemiColon
TerranBuild/SCV=K,P
TerranBuild/SISCV=J,SemiColon
TerranBuild/TychusSCV=J,SemiColon
TerranBuildAdvanced=Slash
TerranBuildAdvanced/HHSCV=Slash
TerranBuildAdvanced/SCV=Slash
TerranBuildAdvanced/SISCV=Slash
TerranInfantryArmorLevel1/EngineeringBay=K
TerranInfantryArmorLevel1/SIEngineeringBay=J
TerranInfantryArmorVanadiumPlatingLevel1/EngineeringBay=J
TerranInfantryArmorVanadiumPlatingLevel2/EngineeringBay=J
TerranInfantryArmorVanadiumPlatingLevel3/EngineeringBay=J
TerranInfantryWeaponsLevel1/EngineeringBay=SemiColon
TerranInfantryWeaponsLevel1/SIEngineeringBay=P
TerranInfantryWeaponsUltraCapacitorsLevel1/EngineeringBay=P
TerranInfantryWeaponsUltraCapacitorsLevel2/EngineeringBay=P
TerranInfantryWeaponsUltraCapacitorsLevel3/EngineeringBay=P
TerranShipPlatingLevel1/Armory=E
TerranShipWeaponsLevel1/Armory=P
TerranVehicleAndShipPlatingLevel1/Armory=K
TerranVehicleAndShipPlatingLevel1/SIArmory=J
TerranVehicleAndShipWeaponsLevel1/Armory=P
TerranVehicleAndShipWeaponsLevel1/SIArmory=P
TerranVehicleWeaponsLevel1/Armory=SemiColon
Thor/Factory=Apostrophe
TimeWarp/Nexus=J
ToxicNestExplode/ToxicNest=J
TrainHHBomber/HHBomberPlatform=J
Transfusion/EvolutionChamber=Minus
Transfusion/Queen=K
Transfusion/QueenCoop=M
TransportMode/WarpPrism=P
TransportMode/ZeratulWarpPrismPhasing=SemiColon
TwilightCouncil/Probe=Apostrophe
TychusACBandofBrothersLearn/TychusMercCompound=Equals
TychusACHero/TychusResearchCenter=P
TychusACImplosionGrenadesLearn/TychusMercCompound=P
TychusACPiercingRoundsLearn/TychusMercCompound=M
TychusACRageGrenadesLearn/TychusMercCompound=Minus
TychusArmory/TychusSCV=Equals
TychusCommandCenter/TychusSCV=Apostrophe
TychusEngineeringBay/TychusSCV=Minus
TychusFirebat/TychusResearchCenter=H
TychusFirebatBlueFlameOilLearn/TychusArmory=Minus
TychusFirebatIncendiaryPetroleumLearn/TychusArmory=M
TychusFirebatPremiumPetroleumLearn/TychusArmory=P
TychusFirebatShieldLearn/TychusArmory=Equals
TychusGhost/TychusResearchCenter=BracketOpen
TychusGhostAcademy/TychusSCV=M
TychusGhostConcentrationHelmetLearn/TychusGhostAcademy=Equals
TychusGhostConfusingDominationLearn/TychusGhostAcademy=Minus
TychusGhostDominateBuffLearn/TychusGhostAcademy=P
TychusGhostPsychicSnare/TychusGhost=BracketOpen
TychusGhostPsychicSnareLearn/TychusGhostAcademy=M
TychusHERC/TychusResearchCenter=SemiColon
TychusHercCrit/TychusArmory=BracketClose
TychusHercGrappleArmor/TychusArmory=BracketOpen
TychusHercGrappleImpacts/TychusArmory=J
TychusHercRageLearn/TychusArmory=Apostrophe
TychusHeroCommonAbil1=J
TychusHeroCommonAbil2=SemiColon
TychusHeroCommonAbil3=Minus
TychusHeroCommonAbil4=H
TychusHeroCommonAbil5=M
TychusMarauder/TychusResearchCenter=N
TychusMarauderAttackSplashLearn/TychusArmory=G
TychusMarauderHealingWardBuffLearn/TychusArmory=SemiColon
TychusMarauderHealingWardSpeedBuffLearn/TychusArmory=H
TychusMarauderSuperStim/TychusMarauder=BracketOpen
TychusMarauderSuperStimLearn/TychusArmory=N
TychusMedic/TychusResearchCenter=M
TychusMedicDefensiveMatrix/TychusMedic=Apostrophe
TychusMedicDefensiveMatrixLearn/TychusGhostAcademy=G
TychusMedicDoubleHealLearn/TychusGhostAcademy=N
TychusMedicHeal/TychusMedic=BracketOpen
TychusMedicHealUpgrade/TychusGhostAcademy=H
TychusMedicHealingSprayUpgrade/TychusGhostAcademy=SemiColon
TychusMedicTransportUnits/TychusMedivacPlatform=J
TychusMercCompound/TychusSCV=N
TychusOdinRedButton/TychusOdin=N
TychusOutlawArmorLevel1/TychusEngineeringBay=J
TychusOutlawWeaponsLevel1/TychusEngineeringBay=P
TychusReaper/TychusResearchCenter=Minus
TychusReaperBombChargesLearn/TychusMercCompound=BracketClose
TychusReaperBombDamageLearn/TychusMercCompound=J
TychusReaperBombStunLearn/TychusMercCompound=BracketOpen
TychusReaperEvasionBuff/TychusReaper=BracketOpen
TychusReaperEvasionLearn/TychusMercCompound=Apostrophe
TychusRefinery/TychusSCV=H
TychusSCV/TychusCommandCenter=SemiColon
TychusSCVAutoTurret/TychusSCV=SemiColon
TychusSpectre/TychusResearchCenter=Apostrophe
TychusSpectreBrillianceAuraLearn/TychusGhostAcademy=BracketClose
TychusSpectreExtendedPulseGunLearn/TychusGhostAcademy=Apostrophe
TychusSpectreSuperUltrasonicPulseLearn/TychusGhostAcademy=J
TychusSpectreVisionSuitLearn/TychusGhostAcademy=BracketOpen
TychusSquadAttackSpeed/TychusEngineeringBay=SemiColon
TychusSquadDetection/TychusEngineeringBay=BracketOpen
TychusSquadHealth/TychusEngineeringBay=Minus
TychusUpgradeOdinRedButton/TychusEngineeringBay=H
TychusWarhound/TychusResearchCenter=J
TychusWarhoundDeathExplosionUpgrade/TychusMercCompound=N
TychusWarhoundFearUpgrade/TychusMercCompound=H
TychusWarhoundHaywireMissiles/TychusWarhound=BracketOpen
TychusWarhoundHaywireMissilesUpgrade/TychusMercCompound=SemiColon
TychusWarhoundTurretHaywireMissiles/TychusWarhoundAutoTurret=J
TychusWarhoundTurretUpgrade/TychusMercCompound=G
Ultralisk/Larva=Backspace
UltraliskCavern/Drone=Minus
Unsiege=P
UpgradeBuildingArmorLevel1/EngineeringBay=Slash
UpgradeToPlanetaryFortress/CommandCenter=K
UpgradeToRoboticsFacilityWarp/RoboticsFacility=M
UpgradeToStargateWarp/Stargate=Apostrophe
UpgradeToWarpGate/Gateway=C
VespeneDrone/CommandCenter=R
VespeneDrone/PlanetaryFortress=R
VikingFighter/HHStarport=P
VikingFighter/Starport=SemiColon
Viper/Larva=Equals
Viper/MutaliskViper=SemiColon
ViperConsume/Viper=BracketOpen
ViperConsumption/Viper=BracketOpen
VoidDarkTemplarShadowFury/DarkTemplarShakuras=SemiColon
VoidHighTemplarMindBlast/HighTemplarTaldarim=SemiColon
VoidHighTemplarPsiOrb/HighTemplarTaldarim=J
VoidRay/Stargate=Slash
VoidRay/StargateWarp=SemiColon
VoidRay/SuperWarpGate=Equals
VoidRayHallucination/Sentry=Equals
VoidRaySwarmDamageBoost/VoidRay=K
VoidSentryChronoBeam/SentryPurifier=Minus
VoidSentryMobileMode/SentryFenix=SemiColon
VoidSentryMobileMode/SentryPurifier=SemiColon
VoidSentryPhasingMode/SentryFenix=J
VoidSentryPhasingMode/SentryPurifier=J
VoidSentryShieldRepair/Sentry=M
VoidSentryShieldRepair/ZeratulSentry=M
VoidSentryShieldRepairDouble/SentryAiur=M
VoidShadowGuardShadowFury/VorazunShadowGuard=SemiColon
VoidShieldCapacitor/FenixCoop=Minus
VoidStasis/DarkTemplarShakuras=Minus
VoidStasis/DarkTemplarTaldarim=Minus
VoidStasis/VorazunShadowGuard=Minus
VoidSwarmHostSpawnLocust/SwarmHostBurrowedMP=J
VoidSwarmHostSpawnLocust/SwarmHostMP=K
VoidZealotShadowCharge/ZealotShakuras=Minus
VoidZealotShadowChargeStun/ZealotShakuras=J
VoidZealotWhirlwind/ZealotAiur=J
VoidZealotWhirlwind/ZeratulSummonZealot=J
VoodooShield/Spectre=SemiColon
Vulture/Factory=J
WarpInAdept/Gateway=Slash
WarpInAdept/WarpGate=Slash
WarpInScout/Stargate=BracketOpen
WarpInScout/SuperWarpGate=G
WarpInZeratulWarpPrism/ZeratulRoboticsFacility=SemiColon
WarpPrism/RoboticsFacility=Slash
WarpPrismHallucination/Sentry=Slash
WarpinDisruptor/RoboticsFacility=BracketOpen
WeaponsFree/Ghost=Minus
WeaponsFree/Ghost_BlackOps=BracketOpen
WeaponsFree/NovaCoop=BracketOpen
WidowMine/Factory=P
WidowMineBurrow/HHWidowMine=J
WidowMineBurrow/MutatorWidowMine=J
WidowMineBurrow/WidowMine=K
WidowMineUnburrow/HHWidowMine=SemiColon
WidowMineUnburrow/WidowMine=P
Wraith/HHStarport=Equals
Wraith/Starport=Equals
WraithCloakOff/HHWraith=M
WraithCloakOff/Wraith=M
WraithCloakOn/HHWraith=Minus
WraithCloakOn/Wraith=Minus
YamatoGun=P
ZagaraBileLauncher/Drone=N
ZagaraVoidCoopBanelingBarrage/ZagaraVoidCoop=SemiColon
ZagaraVoidCoopBanelingBarrage/ZagaraVoidCoopBurrowed=SemiColon
ZagaraVoidCoopBanelingSpawner/BanelingNest=SemiColon
ZagaraVoidCoopMassFrenzy/ZagaraVoidCoop=J
ZagaraVoidCoopMassFrenzy/ZagaraVoidCoopBurrowed=J
ZagaraVoidCoopNydusWorm/NydusNetwork=P
ZagaraVoidCoopSpawnHunterKillers/ZagaraVoidCoop=M
ZagaraVoidCoopSpawnHunterKillers/ZagaraVoidCoopBurrowed=M
Zealot=SemiColon
ZealotHallucination/Sentry=BracketClose
ZeratulBlink/ZeratulCoop=J
ZeratulDarkArchonMaelstrom/ZeratulDarkArchon=J
ZeratulDarkArchonMaelstrom/ZeratulHeroDarkArchon=J
ZeratulDarkArchonMindControl/ZeratulDarkArchon=SemiColon
ZeratulDarkArchonMindControl/ZeratulHeroDarkArchon=SemiColon
ZeratulKhaydarinMonolithWarp/ZeratulKhaydarinMonolith=J
ZeratulObserver/ZeratulRoboticsFacility=P
ZeratulPhaseCannonProjectionPassive/ZeratulPhotonCannon=J
ZeratulPurificationNovaTargeted/ZeratulDisruptor=J
ZeratulReflectionShield/ZeratulSentry=Minus
ZeratulShadowCleave/ZeratulCoop=BracketOpen
ZeratulStructureBarrier/ZeratulKhaydarinMonolith=SemiColon
ZeratulStructureBarrier/ZeratulPhotonCannon=SemiColon
ZeratulSummonVoidSeeker/ZeratulCoop=SemiColon
ZeratulWarpPrismAutoUnloadOff/ZeratulWarpPrismPhasing=M
ZeratulWarpPrismAutoUnloadOn/ZeratulWarpPrismPhasing=Minus
ZeratulWarpPrismSelectVoidRift=Apostrophe
ZeratulWarpPrismUnload/ZeratulWarpPrismPhasing=J
ZeratulWarpinDisruptor/ZeratulRoboticsFacility=BracketOpen
ZeratulXelNagaConstructDevolve/ZeratulXelNagaConstruct=J
ZeratulXelNagaConstructPsiBlast/ZeratulXelNagaConstructCyan=Minus
ZeratulXelNagaConstructPsiStorm/ZeratulXelNagaConstructCyan=J
ZergBuild/Drone=K,P
ZergBuildAdvanced/Drone=Slash
Zergling/Larva=SemiColon
Zergling/VoidRiftUnselectable=SemiColon
hydraliskspeed/HydraliskDen=P
overlordspeed=Equals
zergflyerarmor1=K
zergflyerattack1=SemiColon
zerggroundarmor1/EvolutionChamber=K
zerglingattackspeed/SpawningPool=K
zerglingmovementspeed/SpawningPool=SemiColon
zergmeleeweapons1/EvolutionChamber=SemiColon
zergmissileweapons1/EvolutionChamber=P
*/

export {};

class Action {
    name: string;
    key: string;
    ctrl: boolean;
    shift: boolean;
    alt: boolean;

    constructor(name: string, 
        key: string, 
        ctrl: boolean = false, 
        shift: boolean = false, 
        alt: boolean = false)
    {
        this.name = name;
        this.key = key;
        this.ctrl = ctrl;
        this.shift = shift;
        this.alt = alt;
    }
}

class Operation {
    name: string;
    actions: Action[];
    
    constructor(name: string, actions: Action[]) {
        this.name = name;
        this.actions = actions;
    }
}

interface ModelObserver {
    onOperationSuccess(): void
    opOperationFailure(): void
    onActionSuccess(): void
    onActionFailure(): void
}

class Model {
    // set of operations from which the user is supposed to learn
    operationsSet: Operation[] = [];

    // index of the next required action in the current operation
    nextRequiredActionIndex: number = 0;

    // observer that is notified about the model state changes
    observer: ModelObserver;

    lastActionTime: number = 0;

    // stats
    numberOfSuccessfulOperations: number = 0;
    numberOfFailedOperations: number = 0;
    reactionTimes: number[] = [];
    
    getSuccessRate(): number {
        return this.numberOfSuccessfulOperations / (this.numberOfSuccessfulOperations + this.numberOfFailedOperations);
    }

    getAverageReactionTime(): number {
        if (this.reactionTimes.length === 0) {
            return 0;
        }

        // as seconds
        return this.reactionTimes.reduce((a, b) => a + b, 0) / this.reactionTimes.length / 1000;
    }

    getScore(): number {
        // ideal apm is 300 which is 5 actions per second which is 200ms of reaction time
        // ideal success rate is 1
        // ideal score is 100
        const successRate = this.getSuccessRate();
        const averageReactionTime = this.getAverageReactionTime();
        const score = (successRate + (0.2 / averageReactionTime)) * 50;
        return score;
    }

    // returns the next required operation or null if there are no more operations
    getNextRequiredOperation(): Operation | null {
        if (this.operationsSet.length === 0) {
            return null;
        }

        return this.operationsSet[0];
    }

    // selects the next required action or null if there are no more operations
    getNextRequiredAction(): Action | null {
        const requiredOperation = this.getNextRequiredOperation();
        if (requiredOperation === null) {
            return null;
        }

        return requiredOperation.actions[this.nextRequiredActionIndex];
    }

    registerKey(key: string, ctrl: boolean, shift: boolean, alt: boolean): boolean {
        const requiredOperation = this.getNextRequiredOperation();
        const requiredAction = this.getNextRequiredAction();
        if (requiredAction === null || requiredOperation === null) {
            return false;
        }

        // log information about registered key
        var message = ''
        if (ctrl) {
            message += 'CTRL + ';
        }
        if (shift) {
            message += 'SHIFT + ';
        }
        if (alt) {
            message += 'ALT + ';
        }
        message += key;
        console.log(message);

        if (requiredAction.key === key &&
            requiredAction.ctrl === ctrl &&
            requiredAction.shift === shift &&
            requiredAction.alt === alt) 
        {
            this.nextRequiredActionIndex++;
            this.observer.onActionSuccess();
            if (this.nextRequiredActionIndex === requiredOperation.actions.length) {
                this.observer.onOperationSuccess();
                this.numberOfSuccessfulOperations++;
                this.nextRequiredActionIndex = 0;
                this.operationsSet.shift();
                this.reactionTimes.push(Date.now() - this.lastActionTime);
                this.lastActionTime = Date.now();
            }
            return true;
        } else {
            this.observer.onActionFailure();
            this.numberOfFailedOperations++;
            this.nextRequiredActionIndex = 0;
            return false;
        }
    }

    generateOperationsSet(allowedOperations: Operation[], numberOfOperations: number): void {
        this.operationsSet = [];
        for (let i = 0; i < numberOfOperations; i++) {
            const randomIndex = Math.floor(Math.random() * allowedOperations.length);
            this.operationsSet.push(allowedOperations[randomIndex]);
        }
    }

    constructor(observer: ModelObserver) {
        this.observer = observer;
        this.lastActionTime = Date.now();
    }
}

class View implements ModelObserver {
    canvas: HTMLCanvasElement;
    context: CanvasRenderingContext2D;

    pressedKeys: string[] = [];

    model: Model;

    onKeyDown(event: KeyboardEvent): void {
        // if key is already pressed we should not register it again
        if (this.pressedKeys.includes(event.code)) {
            return;
        }

        this.pressedKeys.push(event.code);
        
        // if event.code does not contain control, alt or shift we can register the key
        if (!event.code.includes('Control') && !event.code.includes('Alt') && !event.code.includes('Shift')) {
            const ctrl = this.pressedKeys.includes('ControlLeft') || this.pressedKeys.includes('ControlRight');
            const alt = this.pressedKeys.includes('AltLeft') || this.pressedKeys.includes('AltRight');
            this.model.registerKey(event.code, ctrl, event.shiftKey, alt);
        }

        this.update();
        event.preventDefault();
    }

    onKeyUp(event: KeyboardEvent): void {
        this.pressedKeys = [];
        this.update();
        event.preventDefault();
    }

    onWindowResize(): void {
        this.canvas.width = window.innerWidth;
        this.canvas.height = window.innerHeight;
        this.update();
    }

    update(): void {
        this.context.clearRect(0, 0, this.canvas.width, this.canvas.height);
        this.drawCurrentAction();
        this.drawExpectedOperations();
        this.drawStatistics();
    }

    drawExpectedOperations(): void {
        // list of operations to execute should be displayed on the left side of the canvas going 
        // from the top to the middle of the canvas
        // each operation should be displayed in a separate line
        // first operation from the list should be displayed in the middle, the next one one line 
        // above and so on until we run out of space

        this.context.fillStyle = 'black';
        this.context.font = '30px Arial';
        this.context.textAlign = 'left';
        this.context.textBaseline = 'middle';

        const operations = this.model.operationsSet;
        const operationsCount = operations.length;
        const lineHeight = 40;
        const startY = this.canvas.height / 2;
        const maxLines = Math.floor(startY / lineHeight);
        
        for (let i = 0; i < operationsCount && i < maxLines; i++) {
            this.context.fillText(operations[i].name, 10, startY - i * lineHeight);
        }

        // draw a frame around the first operation (from left side of the canvas to the 1/3 of the width)
        this.context.strokeStyle = 'black';
        this.context.lineWidth = 3;
        this.context.strokeRect(0, startY - lineHeight / 2, this.canvas.width / 3, lineHeight);
    }

    drawCurrentAction(): void {
        // draw pressed keys in the middle of the canvas
        this.context.fillStyle = 'black';
        this.context.font = '30px Arial';
        this.context.textAlign = 'center';
        this.context.textBaseline = 'middle';
        this.context.fillText(this.pressedKeys.join(' + '), this.canvas.width / 2, this.canvas.height / 2);

        // draw a frame around the pressed keys (from 1/3 of the width to 2/3 of the width)
        this.context.strokeStyle = 'black';
        this.context.lineWidth = 3;
        this.context.strokeRect(this.canvas.width / 3, this.canvas.height / 2 - 20, this.canvas.width / 3, 40);
    }

    drawStatistics(): void {
        // draw statistics on the right side of the canvas
        // statistics should contain the following information:
        // - success rate
        // - average reaction time
        // - score
        // - number of successful operations
        // - number of failed operations

        this.context.fillStyle = 'black';
        this.context.font = '30px Arial';
        this.context.textAlign = 'left';
        this.context.textBaseline = 'top';

        const successRate = this.model.getSuccessRate();
        const averageReactionTime = this.model.getAverageReactionTime();
        const score = this.model.getScore();
        const successfulOperations = this.model.numberOfSuccessfulOperations;
        const failedOperations = this.model.numberOfFailedOperations;

        // limit number of digits to two after the decimal point
        this.context.fillText('Success rate: ' + successRate.toFixed(2), this.canvas.width * 2 / 3, 10);
        this.context.fillText('Average reaction time: ' + averageReactionTime.toFixed(2), this.canvas.width * 2 / 3, 50);
        this.context.fillText('Score: ' + score.toFixed(2), this.canvas.width * 2 / 3, 90);
        this.context.fillText('Successful operations: ' + successfulOperations, this.canvas.width * 2 / 3, 130);
        this.context.fillText('Failed operations: ' + failedOperations, this.canvas.width * 2 / 3, 170);
    }

    generateOperationsSet(allowedOperations: Operation[], numberOfOperations: number): void {
        this.model.generateOperationsSet(allowedOperations, numberOfOperations);
        this.update();
    }

    onOperationSuccess(): void {
        // notify the user that the operation was successful
        // play a sound
        // update the statistics
        this.refreshHintIfShown();
    }

    opOperationFailure(): void {
        // notify the user that the operation was not successful
        // play a sound
        // update the statistics
        this.refreshHintIfShown();
    }

    onActionSuccess(): void {
        // notify the user that the action was successful
        // play a sound
        // update the statistics
        this.refreshHintIfShown();
    }

    onActionFailure(): void {
        // notify the user that the action was not successful
        // play a sound
        // update the statistics
        this.refreshHintIfShown();
    }

    refreshHintIfShown(): void {
        const hintDisplay = document.getElementById('hint-display') as HTMLDivElement;
        if (hintDisplay && !hintDisplay.classList.contains('hidden')) {
            this.showHint();
        }
    }

    constructor() {
        this.canvas = document.getElementById('canvas') as HTMLCanvasElement;
        this.context = this.canvas.getContext('2d') as CanvasRenderingContext2D;

        // set canvas size to the window size
        this.canvas.width = window.innerWidth;
        this.canvas.height = window.innerHeight;

        this.model = new Model(this);
        
        document.addEventListener('keydown', this.onKeyDown.bind(this));
        document.addEventListener('keyup', this.onKeyUp.bind(this));
        window.addEventListener('resize', this.onWindowResize.bind(this));

        // Setup hint button functionality
        this.setupHintButton();

        this.update();
    }

    setupHintButton(): void {
        const hintButton = document.getElementById('hint-button') as HTMLButtonElement;
        const hintDisplay = document.getElementById('hint-display') as HTMLDivElement;
        
        if (hintButton && hintDisplay) {
            hintButton.addEventListener('click', () => {
                this.toggleHintDisplay();
            });
        }
    }

    toggleHintDisplay(): void {
        const hintDisplay = document.getElementById('hint-display') as HTMLDivElement;
        const hintButton = document.getElementById('hint-button') as HTMLButtonElement;
        if (!hintDisplay || !hintButton) return;

        if (hintDisplay.classList.contains('hidden')) {
            this.showHint();
            hintButton.textContent = 'Hide Hint';
        } else {
            this.hideHint();
            hintButton.textContent = 'Show Hotkey Hint';
        }
    }

    showHint(): void {
        const hintDisplay = document.getElementById('hint-display') as HTMLDivElement;
        if (!hintDisplay) return;

        const currentAction = this.model.getNextRequiredAction();
        if (currentAction) {
            const hotkey = this.formatHotkey(currentAction);
            hintDisplay.textContent = `Next hotkey: ${hotkey}`;
            hintDisplay.classList.remove('hidden');
            hintDisplay.classList.add('show');
        } else {
            hintDisplay.textContent = 'No action required at the moment';
            hintDisplay.classList.remove('hidden');
            hintDisplay.classList.add('show');
        }
    }

    hideHint(): void {
        const hintDisplay = document.getElementById('hint-display') as HTMLDivElement;
        if (!hintDisplay) return;

        hintDisplay.classList.remove('show');
        hintDisplay.classList.add('hidden');
    }

    formatHotkey(action: Action): string {
        let hotkey = '';
        
        if (action.ctrl) hotkey += 'Ctrl + ';
        if (action.shift) hotkey += 'Shift + ';
        if (action.alt) hotkey += 'Alt + ';
        
        // Convert the key code to a more readable format
        const keyMap: { [key: string]: string } = {
            'KeyA': 'A', 'KeyB': 'B', 'KeyC': 'C', 'KeyD': 'D', 'KeyE': 'E', 'KeyF': 'F',
            'KeyG': 'G', 'KeyH': 'H', 'KeyI': 'I', 'KeyJ': 'J', 'KeyK': 'K', 'KeyL': 'L',
            'KeyM': 'M', 'KeyN': 'N', 'KeyO': 'O', 'KeyP': 'P', 'KeyQ': 'Q', 'KeyR': 'R',
            'KeyS': 'S', 'KeyT': 'T', 'KeyU': 'U', 'KeyV': 'V', 'KeyW': 'W', 'KeyX': 'X',
            'KeyY': 'Y', 'KeyZ': 'Z',
            'Digit0': '0', 'Digit1': '1', 'Digit2': '2', 'Digit3': '3', 'Digit4': '4',
            'Digit5': '5', 'Digit6': '6', 'Digit7': '7', 'Digit8': '8', 'Digit9': '9',
            'Semicolon': ';', 'Quote': "'", 'Backslash': '\\', 'Slash': '/', 
            'Period': '.', 'Comma': ',', 'Minus': '-', 'Equal': '=',
            'BracketLeft': '[', 'BracketRight': ']', 'Backspace': 'Backspace'
        };
        
        hotkey += keyMap[action.key] || action.key;
        
        return hotkey;
    }
}

// actions

// hatchery
const spawnQueen = new Action('Spawn Queen', 'Quote');
const researchBurrow = new Action('Research Burrow', 'Backslash');
const researchOvSpeed = new Action('Research Ov Speed', 'Equal');
const upgradeToLair = new Action('Upgrade to Lair', 'Backspace');
const upgradeToHive = new Action('Upgrade to Hive', 'Backspace');

// units
const morphZergling = new Action('Morph Zergling', 'Semicolon');
const morphDrone = new Action('Morph Drone', 'KeyP');
const morphRoach = new Action('Morph Roach', 'KeyK');
const morphOverlord = new Action('Morph Overlord', 'Slash');
const morphHydra = new Action('Morph Hydra', 'BracketLeft');
const morphInfestor = new Action('Morph Infestor', 'Quote');
const morphMutalisk = new Action('Morph Mutalist', 'Period');
const morphCorruptor = new Action('Morph Corruptor', 'Minus');
const morphSwarmHost = new Action('Morph Swarm Host', 'BracketRight');
const morphViper = new Action('Morph Viper', 'Equal');
const morphUltra = new Action('Morph Backspace', 'Backspace');

// buildings
const buildBasic = new Action('Build Basic', 'KeyK');
const buildAdvanced = new Action('Build Advanced', 'Slash');

const buildSpore = new Action('Build Spore', 'Semicolon');
const buildSpawningPool = new Action('Build Spawning Pool', 'KeyK');
const buildRoachWarren = new Action('Build Roach Warren', 'KeyP');
const buildExtractor = new Action('Build Extractor', 'Slash');
const buildSpine = new Action('Build Spine', 'BracketLeft');
const buildEvoChamber = new Action('Build Evo Chamber', 'Quote');
const buildBanelingNest = new Action('Build Baneling Nest', 'Period');
const buildHatchery = new Action('Build Hatchery', 'Minus');

const buildSpire = new Action('Build Spire', 'Semicolon');
const buildHydraDen = new Action('Build Hydra Den', 'KeyK');
const buildInfestationPit = new Action('Build Infestation Pit', 'KeyP');
const buildLurkerDen = new Action('Build Lurker Den', 'BracketLeft');
const buildNydusNetwork = new Action('Build Nydus Network', 'Quote');
const buildUltraCavern = new Action('Build Ultra Cavern', 'Backspace');

// overlord
const morphDropLord = new Action('Morph Drop Lord', 'KeyK');
const morphOverseer = new Action('Morph Overseer', 'KeyP');
const unloadDropLord = new Action('Unload Drop Lord', 'Slash');
const ovSpreadCreep = new Action('Ov Spread Creep', 'BracketLeft');

// units

const burrow = new Action('Burrow', 'BracketLeft');
const unburrow = new Action('Unburrow', 'BracketRight');
const morphLurker = new Action('Morph Lurker', 'KeyP');
const morphRavager = new Action('Morph Ravager', 'KeyP');
const morphBaneling = new Action('Morph Baneling', 'KeyP');
const morphBroodlord = new Action('Morph Broodlord', 'KeyP');

// infestor
const fungalGrowth = new Action('Fungal Growth', 'KeyK');
const neuralParasite = new Action('Neural Parasite', 'Slash');

const addToInjectQueens = new Action('Add to Inject Queens', 'KeyI', true, false, false);
const addToHatcheries = new Action('Add to Hatcheries', 'KeyO', true, false, false);
const addToHarassArmy = new Action('Add to Harass Army', 'KeyJ', true, false, false);
const addToMainArmy = new Action('Add to Main Army', 'KeyL', true, false, false);
const addToCreepQueens = new Action('Add to Creep Queens', 'KeyH', true, false, false);

const selectInjectQueens = new Action('Select Inject Queens', 'KeyI');
const selectHatcheries = new Action('Select Hatcheries', 'KeyO');
const selectHarassArmy = new Action('Select Harass Army', 'KeyJ');
const selectMainArmy = new Action('Select Main Army', 'KeyL');
const selectCreepQueens = new Action('Select Creep Queens', 'KeyH');

const createCameraLocation1 = new Action('Create Camera Location 1', 'Digit0', true, false, true);
const createCameraLocation2 = new Action('Create Camera Location 2', 'Digit9', true, false, true);
const createCameraLocation3 = new Action('Create Camera Location 3', 'Digit8', true, false, true);
const createCameraLocation4 = new Action('Create Camera Location 4', 'KeyU', true, false, true);

const goToCameraLocation1 = new Action('Go To Camera Location 1', 'Digit0');
const goToCameraLocation2 = new Action('Go To Camera Location 2', 'Digit9');
const goToCameraLocation3 = new Action('Go To Camera Location 3', 'Digit8');
const goToCameraLocation4 = new Action('Go To Camera Location 4', 'KeyU');

// operations

// just every action gets its own operation - later we'll add more compilcated operations

const allowedOperations = [
    new Operation('Spawn Queen', [spawnQueen]),
    new Operation('Research Burrow', [researchBurrow]),
    new Operation('Research Ov Speed', [researchOvSpeed]),
    new Operation('Upgrade to Lair', [upgradeToLair]),
    new Operation('Upgrade to Hive', [upgradeToHive]),
    new Operation('Morph Zergling', [morphZergling]),
    new Operation('Morph Drone', [morphDrone]),
    new Operation('Morph Roach', [morphRoach]),
    new Operation('Morph Overlord', [morphOverlord]),
    new Operation('Morph Hydra', [morphHydra]),
    new Operation('Morph Infestor', [morphInfestor]),
    new Operation('Morph Mutalisk', [morphMutalisk]),
    new Operation('Morph Corruptor', [morphCorruptor]),
    new Operation('Morph Swarm Host', [morphSwarmHost]),
    new Operation('Morph Viper', [morphViper]),
    new Operation('Morph Ultra', [morphUltra]),
    new Operation('Build Basic', [buildBasic]),
    new Operation('Build Advanced', [buildAdvanced]),
    new Operation('Build Spore', [buildSpore]),
    new Operation('Build Spawning Pool', [buildSpawningPool]),
    new Operation('Build Roach Warren', [buildRoachWarren]),
    new Operation('Build Extractor', [buildExtractor]),
    new Operation('Build Spine', [buildSpine]),
    new Operation('Build Evo Chamber', [buildEvoChamber]),
    new Operation('Build Baneling Nest', [buildBanelingNest]),
    new Operation('Build Hatchery', [buildHatchery]),
    new Operation('Build Spire', [buildSpire]),
    new Operation('Build Hydra Den', [buildHydraDen]),
    new Operation('Build Infestation Pit', [buildInfestationPit]),
    new Operation('Build Lurker Den', [buildLurkerDen]),
    new Operation('Build Nydus Network', [buildNydusNetwork]),
    new Operation('Build Ultra Cavern', [buildUltraCavern]),
    new Operation('Morph Drop Lord', [morphDropLord]),
    new Operation('Morph Overseer', [morphOverseer]),
    new Operation('Unload Drop Lord', [unloadDropLord]),
    new Operation('Ov Spread Creep', [ovSpreadCreep]),
    new Operation('Burrow', [burrow]),
    new Operation('Unburrow', [unburrow]),
    new Operation('Morph Lurker', [morphLurker]),
    new Operation('Morph Ravager', [morphRavager]),
    new Operation('Morph Baneling', [morphBaneling]),
    new Operation('Morph Broodlord', [morphBroodlord]),
    new Operation('Fungal Growth', [fungalGrowth]),
    new Operation('Neural Parasite', [neuralParasite]),
    new Operation('Add to Inject Queens', [addToInjectQueens]),
    new Operation('Add to Hatcheries', [addToHatcheries]),
    new Operation('Add to Harass Army', [addToHarassArmy]),
    new Operation('Add to Main Army', [addToMainArmy]),
    new Operation('Add to Creep Queens', [addToCreepQueens]),
    new Operation('Select Inject Queens', [selectInjectQueens]),
    new Operation('Select Hatcheries', [selectHatcheries]),
    new Operation('Select Harass Army', [selectHarassArmy]),
    new Operation('Select Main Army', [selectMainArmy]),
    new Operation('Select Creep Queens', [selectCreepQueens]),
    new Operation('Create Camera Location 1', [createCameraLocation1]),
    new Operation('Create Camera Location 2', [createCameraLocation2]),
    new Operation('Create Camera Location 3', [createCameraLocation3]),
    new Operation('Create Camera Location 4', [createCameraLocation4]),
    new Operation('Go To Camera Location 1', [goToCameraLocation1]),
    new Operation('Go To Camera Location 2', [goToCameraLocation2]),
    new Operation('Go To Camera Location 3', [goToCameraLocation3]),
    new Operation('Go To Camera Location 4', [goToCameraLocation4]),
];

const view = new View();
view.generateOperationsSet(allowedOperations, 50);
